---
inputs:
  - type: git
    branch: ${PIPELINE_REPO_BRANCH}
    service: ${PIPELINE_REPO}
    path: .pipeline
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: git
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: container-registry
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: master
    path: kubernetes-service
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: master
    path: toolchain
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: master
    path: devops-insights
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: linter
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: tester
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: utils
triggers:
  - type: git
    name: commit-push
    eventListener: ${GIT_COMMIT_EVENT_LISTENER_NAME}
    service: ${APP_REPO}
    branch: master
    events: { "push": true }
  - type: manual
    name: manual-run
    eventListener: manual-run
    properties: []
properties:
  - name: toolchain-apikey
    value: prod-env
    type: INTEGRATION
    path: parameters.properties.api-key
  - name: apikey
    value: prod-env
    type: INTEGRATION
    path: parameters.properties.api-key
  - name: registry-region
    value: prod-env
    type: INTEGRATION
    path: parameters.properties.registry-region
  - name: registry-namespace
    value: prod-env
    type: INTEGRATION
    path: parameters.properties.registry-namespace
  - name: image-name
    value: ${APP_NAME}
    type: text
  - name: app-name
    value: ${APP_NAME}
    type: text
  - name: dev-cluster-namespace
    value: prod-env
    type: INTEGRATION
    path: parameters.properties.cluster-namespace
  - name: dev-region
    value: prod-env
    type: INTEGRATION
    path: parameters.properties.region
  - name: cluster-name
    value: prod-env
    type: INTEGRATION
    path: parameters.properties.cluster-name
  - name: dev-resource-group
    value: prod-env
    type: INTEGRATION
    path: parameters.properties.resource-group
